// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfeg1jQfz0s-FhecjRLfTKoYZdny1y6d8',
    appId: '1:534422137450:web:96476526a6c6cec2067813',
    messagingSenderId: '534422137450',
    projectId: 'e-block-rewards',
    authDomain: 'e-block-rewards.firebaseapp.com',
    storageBucket: 'e-block-rewards.firebasestorage.app',
    measurementId: 'G-Y8PJSGPJXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuINkUOTqWKNn5sjmJ6CJaGW6amELI948',
    appId: '1:534422137450:android:aa5a157a985fbbe2067813',
    messagingSenderId: '534422137450',
    projectId: 'e-block-rewards',
    storageBucket: 'e-block-rewards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARWSXp_4qM5hJr29jxsVJBhgAdm6gb3_U',
    appId: '1:534422137450:ios:5dac18aca95c3fd3067813',
    messagingSenderId: '534422137450',
    projectId: 'e-block-rewards',
    storageBucket: 'e-block-rewards.firebasestorage.app',
    iosBundleId: 'com.example.eblockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARWSXp_4qM5hJr29jxsVJBhgAdm6gb3_U',
    appId: '1:534422137450:ios:5dac18aca95c3fd3067813',
    messagingSenderId: '534422137450',
    projectId: 'e-block-rewards',
    storageBucket: 'e-block-rewards.firebasestorage.app',
    iosBundleId: 'com.example.eblockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfeg1jQfz0s-FhecjRLfTKoYZdny1y6d8',
    appId: '1:534422137450:web:e1b16def16a2e5d3067813',
    messagingSenderId: '534422137450',
    projectId: 'e-block-rewards',
    authDomain: 'e-block-rewards.firebaseapp.com',
    storageBucket: 'e-block-rewards.firebasestorage.app',
    measurementId: 'G-3W2VGJFGFT',
  );
}
